ignore = [
  # codegen
  # must be in sync with .gitignore
  "src/parser/parse.rs",
  "src/reserved_words/list.rs",
  "src/tests/fixtures/lexer/gen",
  "src/tests/fixtures/parser/gen",
  "src/tests/lexer/gen.rs",
  "src/tests/parser/gen.rs",
]
