name: codegen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  codegen:
    name: check codegen
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"

      - name: install ragel
        run: |
          sudo apt-get update
          sudo apt-get install ragel

      - name: run codegen
        run: make codegen-tests

      - name: assert no diff
        run: |
          git add .
          git diff --staged --exit-code
