name: release-codegen

on:
  push:
    tags:
      - 'codegen-v*'

defaults:
  run:
    shell: bash

jobs:
  generate-parse-y-and-tokens-rs:
    name: generate parse.rs and target/tokens.rs
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.build.target }}
          override: true

      - name: setup bison
        uses: bison-packages/install-bison@v1
        with:
          version: '3.8.2'

      - name: generate parse.rs
        run: cargo check --features=development

      - name: save generated parse.rs
        uses: actions/upload-artifact@v3
        with:
          name: parse.rs
          path: src/parser/parse.rs

      - name: generate target/tokens.rs
        run: cargo run --bin prepare_token_ids --features=bin-prepare_token_ids

      - name: save generated target/tokens.rs
        uses: actions/upload-artifact@v3
        with:
          name: tokens.rs
          path: target/tokens.rs

  build:
    name: target = ${{ matrix.build.target }}
    needs: ['generate-parse-y-and-tokens-rs']
    runs-on: ${{ matrix.build.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - { os: ubuntu-latest,  exe: ,     zig: false, build: build,    target: x86_64-unknown-linux-gnu }
          - { os: macos-latest,   exe: ,     zig: false, build: build,    target: x86_64-apple-darwin      }
          - { os: windows-latest, exe: .exe, zig: false, build: build,    target: x86_64-pc-windows-msvc   }
          - { os: ubuntu-latest,  exe: ,     zig: true,  build: zigbuild, target: aarch64-apple-darwin     }
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.build.target }}
          override: true

      - name: download generated parse.rs
        uses: actions/download-artifact@v3
        with:
          name: parse.rs

      - name: download generated tokens.rs
        uses: actions/download-artifact@v3
        with:
          name: tokens.rs

      - run: mv parse.rs src/parser/parse.rs
      - run: mkdir -p target && mv tokens.rs target/tokens.rs

      - name: codegen all other rust files
        run: cargo build --features=codegen-rust

      - name: install zig
        uses: goto-bus-stop/setup-zig@v2
        if: ${{ matrix.build.zig }}

      - name: install cargo-zigbuild
        run: cargo install cargo-zigbuild
        if: ${{ matrix.build.zig }}

      - name: compile codegen
        run: cargo ${{ matrix.build.build }} --bin codegen --features=bin-codegen --release --target ${{ matrix.build.target }}

      - name: give executable representable name
        run: cp target/${{ matrix.build.target }}/release/codegen${{ matrix.build.exe }} ./codegen-${{ matrix.build.target }}${{ matrix.build.exe }}

      - name: upload executable
        uses: actions/upload-artifact@v3
        with:
          name: codegen-${{ matrix.build.target }}${{ matrix.build.exe }}
          path: codegen-${{ matrix.build.target }}${{ matrix.build.exe }}

  make-release:
    name: release
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with: { name: codegen-x86_64-unknown-linux-gnu }

      - uses: actions/download-artifact@v3
        with: { name: codegen-x86_64-apple-darwin }

      - uses: actions/download-artifact@v3
        with: { name: codegen-x86_64-pc-windows-msvc.exe }

      - uses: actions/download-artifact@v3
        with: { name: codegen-aarch64-apple-darwin }

      - run: ls -l

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "codegen-*"
          token: ${{ secrets.GITHUB_TOKEN }}
