name: test-rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test on ${{ matrix.build.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          - { rust: stable }
          - { rust: beta }
          - { rust: nightly }

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.build.rust }}
          override: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"

      - name: setup bison
        uses: bison-packages/install-bison@v1
        with:
          version: '3.8.2'

      - name: install ragel
        run: |
          sudo apt-get update
          sudo apt-get install ragel

      - name: show bison version
        run: bison --version

      - name: codegen tests
        run: make codegen-tests

      - name: codegen all rust files
        run: cargo check --features=development

      - name: run tests
        run: cargo test
